"""sfvsfvs

Revision ID: 990f289d8956
Revises: cfcae2b88140
Create Date: 2026-04-24 12:59:26.226766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990f289d8956'
down_revision = 'cfcae2b88140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_logs', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('origin',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('destination',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('aircraft_tail_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('pilot_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('submitted_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flight_logs', schema=None) as batch_op:
        batch_op.alter_column('submitted_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('pilot_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('aircraft_tail_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('destination',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('origin',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('date_posted',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
