"""first migration

Revision ID: cfcae2b88140
Revises: 
Create Date: 2026-04-24 11:18:29.327124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfcae2b88140'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('destination', sa.String(length=10), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('aircraft_tail_number', sa.String(length=20), nullable=False),
    sa.Column('pilot_name', sa.String(length=100), nullable=False),
    sa.Column('submitted_by', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_logs')
    # ### end Alembic commands ###
